### ISSUE TITLE
Camera -> Image transformation added to the 'K' matrix

### ISSUE THREAD

**Issue by jiayily** [robin-karlsson0/perspective_mapping#1]
Hi, why do you post-multiply a matrix to K?
`# Camera -> Image transformation added to the 'K' matrix`
`C = K @ np.array([[0, -1, 0], [0, 0, -1], [1, 0,  0]])`

**Comment by robin-karlsson0** [comment]
@Jiayi719 Apologizes for missing your question for so long!

The purpose of the operation is to transform coordinate information in K from the **camera frame** to the **image frame**. The later matrix is a rotation matrix which does that.

Please see the attached image that demonstrate this operation. Will update the notebook to explain this operation better. Thanks for the question :)

![camera_to_image_coordinate_transformation](https://user-images.githubusercontent.com/34254153/119804943-c7ada400-bf1b-11eb-85aa-1c8fc19ff0af.png)

**Comment by jiayily** [comment]
Got it. The camera frame in your code is very strange. Is it defined in the calibration procedure? And why R_cam2img is not a transpose of the matrix in your code? that is `R_cam2img = np.array([[0, -1, 0], [0, 0, -1], [1, 0, 0]]).T`

**Comment by jiayily** [comment]
@robin-karlsson0 
Hi, I think you made some mistakes in the derivation although the result is right. Mine is as follows:
x ---> z
y ---> -x
z ---> -y
